# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class BodyAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, is_done=None):  # noqa: E501
        """BodyAllOf - a model defined in OpenAPI

        :param is_done: The is_done of this BodyAllOf.  # noqa: E501
        :type is_done: bool
        """
        self.openapi_types = {
            'is_done': bool
        }

        self.attribute_map = {
            'is_done': 'is_done'
        }

        self._is_done = is_done

    @classmethod
    def from_dict(cls, dikt) -> 'BodyAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_allOf of this BodyAllOf.  # noqa: E501
        :rtype: BodyAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_done(self):
        """Gets the is_done of this BodyAllOf.

        Si la TODO est marquée finie.  # noqa: E501

        :return: The is_done of this BodyAllOf.
        :rtype: bool
        """
        return self._is_done

    @is_done.setter
    def is_done(self, is_done):
        """Sets the is_done of this BodyAllOf.

        Si la TODO est marquée finie.  # noqa: E501

        :param is_done: The is_done of this BodyAllOf.
        :type is_done: bool
        """
        if is_done is None:
            raise ValueError("Invalid value for `is_done`, must not be `None`")  # noqa: E501

        self._is_done = is_done
