# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.todo import Todo
from openapi_server import util

from openapi_server.models.todo import Todo  # noqa: E501

class InlineResponse200(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, todos=None):  # noqa: E501
        """InlineResponse200 - a model defined in OpenAPI

        :param todos: The todos of this InlineResponse200.  # noqa: E501
        :type todos: List[Todo]
        """
        self.openapi_types = {
            'todos': List[Todo]
        }

        self.attribute_map = {
            'todos': 'todos'
        }

        self._todos = todos

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def todos(self):
        """Gets the todos of this InlineResponse200.


        :return: The todos of this InlineResponse200.
        :rtype: List[Todo]
        """
        return self._todos

    @todos.setter
    def todos(self, todos):
        """Sets the todos of this InlineResponse200.


        :param todos: The todos of this InlineResponse200.
        :type todos: List[Todo]
        """

        self._todos = todos
