# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TodoRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, description=None):  # noqa: E501
        """TodoRequest - a model defined in OpenAPI

        :param title: The title of this TodoRequest.  # noqa: E501
        :type title: str
        :param description: The description of this TodoRequest.  # noqa: E501
        :type description: str
        """
        self.openapi_types = {
            'title': str,
            'description': str
        }

        self.attribute_map = {
            'title': 'title',
            'description': 'description'
        }

        self._title = title
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TodoRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TodoRequest of this TodoRequest.  # noqa: E501
        :rtype: TodoRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this TodoRequest.

        Titre de la TODO.  # noqa: E501

        :return: The title of this TodoRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this TodoRequest.

        Titre de la TODO.  # noqa: E501

        :param title: The title of this TodoRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501
        if title is not None and len(title) > 128:
            raise ValueError("Invalid value for `title`, length must be less than or equal to `128`")  # noqa: E501

        self._title = title

    @property
    def description(self):
        """Gets the description of this TodoRequest.

        Description de la TODO.  # noqa: E501

        :return: The description of this TodoRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TodoRequest.

        Description de la TODO.  # noqa: E501

        :param description: The description of this TodoRequest.
        :type description: str
        """
        if description is not None and len(description) > 280:
            raise ValueError("Invalid value for `description`, length must be less than or equal to `280`")  # noqa: E501

        self._description = description
